import fs from 'node:fs'
import path from 'node:path'

import { scaffold } from '#config/scaffold.js'
import { paths } from '#config/paths.js'
import { styles } from '#config/styles.js'
import { features } from '#config/features.js'

import { env } from '#gulp/utils/env.js'
import { logger } from '#gulp/utils/logger.js'

const isCi = (() => {
  const v = String(process.env.CI || '')
    .trim()
    .toLowerCase()
  return v === '1' || v === 'true' || v === 'yes' || v === 'on'
})()

const allowAuto = () => {
  if (scaffold.mode !== 'auto') return false
  if (scaffold.devOnly && !env.isDev) return false
  if (isCi) return false
  return true
}

const statSafe = p => {
  try {
    return fs.statSync(p)
  } catch {
    return null
  }
}

const ensureDir = dir => {
  const st = statSafe(dir)
  if (st?.isDirectory()) return false
  fs.mkdirSync(dir, { recursive: true })
  return true
}

const ensureFile = (file, content = '') => {
  const st = statSafe(file)
  if (st?.isFile()) return false
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content, 'utf8')
  return true
}

const failMissing = (what, p) => {
  const rel = path.relative(process.cwd(), p).replace(/\\/g, '/')
  throw new Error(
    `[scaffold] Missing ${what}: ${rel}\n` +
      `Create it manually (recommended) or set config/scaffold.js -> mode: "auto" to allow dev-only scaffolding.`,
  )
}

const entryStylesPath = () => {
  switch (styles.engine) {
    case 'css':
      return paths.styles.entryCss
    case 'tailwind':
      return paths.styles.entryTailwind
    case 'scss':
    default:
      return paths.styles.entryScss
  }
}

export const scaffoldTask = async () => {
  const auto = allowAuto()

  const baseDirs = [
    paths.src,
    path.join(paths.src, 'pages'),
    path.join(paths.src, 'shared'),
    path.join(paths.src, 'styles'),
    path.join(paths.src, 'scripts'),
    path.join(paths.src, 'assets'),
    paths.assets.imagesBase,
    paths.assets.iconsBase,
    path.join(paths.src, 'assets', 'fonts'),

    ...(features.favicons?.enabled === false ? [] : [paths.assets.faviconsBase]),
  ]

  const created = []
  const missing = []

  for (const d of baseDirs) {
    if (auto) {
      if (ensureDir(d)) created.push(d)
    } else {
      if (!statSafe(d)?.isDirectory())
        missing.push({
          what: 'directory',
          path: d,
        })
    }
  }

  const entries = [
    {
      what: 'scripts entry',
      path: paths.scripts.entry,
      content: `// Entry point (generated by scaffold in dev).\n\n`,
    },
    {
      what: 'styles entry',
      path: entryStylesPath(),
      content:
        styles.engine === 'scss'
          ? `// Entry point (generated by scaffold in dev)\n\n`
          : `/* Entry point (generated by scaffold in dev) */\n\n`,
    },
  ]

  for (const e of entries) {
    if (auto) {
      if (ensureFile(e.path, e.content)) created.push(e.path)
    } else {
      if (!statSafe(e.path)?.isFile())
        missing.push({
          what: e.what,
          path: e.path,
        })
    }
  }

  if (!auto && missing.length) {
    failMissing(missing[0].what, missing[0].path)
  }

  if (created.length) {
    const msg = `created ${created.length} item(s)`
    if (scaffold.verbose) {
      logger.info('scaffold', msg)
      for (const p of created)
        logger.info('scaffold', `  - ${path.relative(process.cwd(), p).replace(/\\/g, '/')}`)
    } else {
      logger.dev('scaffold', msg)
    }
  }
}
